name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@0e769ba8c6b8cfd3826b206c4d529b48d450c8f1 # 0.9.2
